"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from importlib.util import find_spec
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default=False):
    value = os.environ.get(name)

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    os.environ.get(
        "SECRET_KEY",
        "django-insecure-qd(_mh9#&$bjhz$1qo6@=tj!2pvlh)%chh*=ogig=!!zo@3o)@",
    ),
)

RUNNING_ON_RENDER = bool(os.environ.get("RENDER"))
LOCAL_DRIVE_SCANNER_ENABLED = _env_bool(
    "DRIVE_AGENT_ENABLE_LOCAL_SCANNER",
    default=not RUNNING_ON_RENDER,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=not RUNNING_ON_RENDER)

_default_allowed_hosts = ["127.0.0.1", "localhost"]

if os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    _default_allowed_hosts.append(os.environ["RENDER_EXTERNAL_HOSTNAME"])

if DEBUG:
    _default_allowed_hosts.append("*")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", ",".join(_default_allowed_hosts)).split(",")
    if host.strip()
]

_default_csrf_origins = []

if os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    _default_csrf_origins.append(f"https://{os.environ['RENDER_EXTERNAL_HOSTNAME']}")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", ",".join(_default_csrf_origins)).split(",")
    if origin.strip()
]


# Application definition

HAS_WHITENOISE = find_spec("whitenoise") is not None

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drivefiles.apps.DrivefilesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SQLITE_DATABASE_URL = f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if RUNNING_ON_RENDER and not DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL is required on Render so users, passwords, and agent data "
        "are stored permanently in PostgreSQL instead of temporary SQLite."
    )

if dj_database_url is not None:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL or SQLITE_DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    DATABASES["default"].setdefault("OPTIONS", {})["timeout"] = 30


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if HAS_WHITENOISE
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}
WHITENOISE_USE_FINDERS = DEBUG

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "drive_files"
LOGOUT_REDIRECT_URL = "login"
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_NAME = f"file_agent_session_{secrets.token_hex(8)}"
AGENT_API_TOKEN = os.environ.get("DRIVE_AGENT_API_TOKEN", "drive-agent-local-token")
AGENT_ONLINE_SECONDS = max(
    1,
    min(3, int(os.environ.get("DRIVE_AGENT_ONLINE_SECONDS", "3"))),
)
AGENT_FILE_BATCH_SIZE = int(os.environ.get("DRIVE_AGENT_FILE_BATCH_SIZE", "1000"))
AGENT_AUTO_SELECT_SINGLE_ACTIVE_AGENT = _env_bool(
    "DRIVE_AGENT_AUTO_SELECT_SINGLE_ACTIVE_AGENT",
    default=True,
)
AGENT_FILE_DOWNLOAD_WAIT_SECONDS = int(
    os.environ.get("DRIVE_AGENT_FILE_DOWNLOAD_WAIT_SECONDS", "20")
)
REMOTE_FILE_DOWNLOAD_ROOT = Path(
    os.environ.get("DRIVE_AGENT_REMOTE_DOWNLOAD_ROOT", BASE_DIR / "remote_downloads")
)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DRIVE_AGENT_MAX_UPLOAD_BYTES", str(50 * 1024 * 1024))
)
