# Generated by Django 6.0.7 on 2026-07-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivefiles', '0002_activeagentdrive_activeagentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('relative_path', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=255)),
                ('modified_timestamp', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=2048)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='activeagentfile',
            new_name='drivefiles__drive_i_3bdfe3_idx',
            old_name='drivefiles__drive_i_3b7a32_idx',
        ),
        migrations.RenameIndex(
            model_name='activeagentfile',
            new_name='drivefiles__drive_i_cd33b6_idx',
            old_name='drivefiles__drive_i_6c8025_idx',
        ),
        migrations.AddField(
            model_name='remotefiledownload',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='drivefiles.activeagent'),
        ),
        migrations.AddField(
            model_name='remotefiledownload',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='drivefiles.activeagentdrive'),
        ),
        migrations.AddIndex(
            model_name='remotefiledownload',
            index=models.Index(fields=['agent', 'drive', 'relative_path'], name='drivefiles__agent_i_7b0a83_idx'),
        ),
        migrations.AddIndex(
            model_name='remotefiledownload',
            index=models.Index(fields=['request_id', 'status'], name='drivefiles__request_be58b4_idx'),
        ),
    ]
