# Generated by Django 6.0.7 on 2026-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivefiles', '0003_remotefiledownload_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activeagentfile',
            index=models.Index(fields=['drive', '-freshness_timestamp', 'name'], name='drivefiles__drive_i_94f34d_idx'),
        ),
        migrations.AddIndex(
            model_name='activeagentfile',
            index=models.Index(fields=['drive', 'type_class'], name='drivefiles__drive_i_024973_idx'),
        ),
        migrations.AddIndex(
            model_name='activeagentfile',
            index=models.Index(fields=['drive', 'extension'], name='drivefiles__drive_i_c0650a_idx'),
        ),
    ]
