# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivefiles", "0004_activeagentfile_drivefiles__drive_i_94f34d_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activeagentfile",
            index=models.Index(
                fields=["drive", "type_class", "-freshness_timestamp", "name"],
                name="df_file_type_fast_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activeagentfile",
            index=models.Index(
                fields=["drive", "extension", "-freshness_timestamp", "name"],
                name="df_file_ext_fast_idx",
            ),
        ),
    ]
