# Generated by Django 5.2.5 on 2026-07-31 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivefiles', '0005_add_fast_file_filter_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeagent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activeagentdrive',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activeagentfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='remotefiledownload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DriveActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('file_added', 'File Added'), ('file_renamed', 'File Renamed'), ('file_deleted', 'File Deleted'), ('external_copy', 'External Copy / Download')], max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('old_name', models.CharField(blank=True, max_length=255)),
                ('details', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='drivefiles.activeagent')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='drivefiles.activeagentdrive')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['drive', '-timestamp'], name='drivefiles__drive_i_e744ea_idx'), models.Index(fields=['agent', '-timestamp'], name='drivefiles__agent_i_2d9669_idx')],
            },
        ),
    ]
