# Generated by Django 5.2.5 on 2026-07-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivefiles', '0006_alter_activeagent_id_alter_activeagentdrive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveactivitylog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='drivefiles.activeagent'),
        ),
        migrations.AlterField(
            model_name='driveactivitylog',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='drivefiles.activeagentdrive'),
        ),
    ]
